name: Deploy document

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: Deploy document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Build documentation
        run: |
          pip3 install -U .
          pip3 install pdoc3
          pdoc --html --config show_source_code=False --force voicevox
      
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/voicevox
          commit_message: Deploy documentation
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com